// Example configuration for MMM-LunchMenu
// Add this to your MagicMirror config/config.js file

{
    module: 'MMM-LunchMenu',
    position: 'bottom_left',  // or any MagicMirror position
    header: 'School Lunch',    // Optional header text
    config: {
        // Path to the menu HTML file generated by the scraper
        // This must match where your scraper outputs the file
        menuUrl: '/modules/MMM-LunchMenu/public/lunch_menu.html',
        
        // How often to refresh the menu (in milliseconds)
        // 3600000 = 1 hour, 1800000 = 30 minutes
        updateInterval: 3600000,
        
        // Display dimensions
        width: '600px',
        height: '400px'
    }
}

// If using Docker with shared volume, your menuUrl might be:
// menuUrl: '/modules/default/public/lunch_menu.html'
//
// Adjust based on your Docker volume mount configuration

